---
- name: Check if Docker is installed
  command: docker --version
  register: docker_installed
  ignore_errors: true
  changed_when: false

- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes
  when: docker_installed.rc != 0

- name: Install required packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present
  when: docker_installed.rc != 0

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  when: docker_installed.rc != 0

- name: Download Docker GPG key
  ansible.builtin.command: install -m 0755 -d /etc/apt/keyrings
  when: docker_installed.rc != 0

- name: Ensure the GPG key has the correct permissions
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'
  when: docker_installed.rc != 0

- name: Add Docker repository to apt sources
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    create: yes
    state: present
  when: docker_installed.rc != 0

- name: Update apt package index again
  ansible.builtin.apt:
    update_cache: yes
  when: docker_installed.rc != 0

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  when: docker_installed.rc != 0
